### ISSUE TITLE
Toolbar moves when fixed on top

### ISSUE THREAD

**Issue by VADERtheSAIYAN** [fengeon/Resprite-doc#38] opened 2023-03-15 18:50 UTC
When you fixing toolbar and tool options on top bar it moves from side to side while 
you pick some tools which have different amount of tool options. Also it moves canvas from side to side which is pain to see every time.  Sometimes it’s impossible to fix toolbar on the top at all. Somehow this feature doesn’t work.

**Comment by fengeon** [comment] 2023-03-16 02:18
> Sometimes it’s impossible to fix toolbar on the top at all. Somehow this feature doesn’t work.

Sometimes not working should be because, when there is not enough space on top, it will not display on top. For example, in the portrait mode of ipad mini6.

> When you fixing toolbar and tool options on top bar it moves from side to side while
you pick some tools which have different amount of tool options. Also it moves canvas from side to side which is pain to see every time. 

I have reproduced this problem under some ipad models. Will be fixed in v1.7 (v1.6 has been submitted to apple). Thanks for your feedback.

**Comment by fengeon** [comment] 2023-03-23 02:50
Optimized in v1.6, close

**Closed by fengeon** 2023-03-23 02:50 UTC
